M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu24.04.1} date 2024-11-13T00:59:24+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-13T00:59:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1358
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1378
%
G90
G05
T1
X3.2976Y1.2986
X3.2976Y1.0711
T2
X3.1602Y1.535
T3
X0.6634Y1.535
X2.8366Y2.165
T4
X0.44Y1.285
X2.525Y0.15
X3.4Y2.15
M30
